public class MathematicaClass {

    public integer add (integer int1, integer int2){
        integer total = int1 + int2;
        return total;
        }

    public integer sub (integer int1, integer int2){
        integer difference = int1 - int2;
        return difference;

    }

    public integer mult (integer int1, integer int2){
        integer product = int1 * int2;
        return product;
    }

    public integer divide (integer int1, integer int2){
        integer div = int1 / int2;
        return div;

    }
}
