Integer sum1= Calculator.add(15,15);
system.debug(sum1);

Integer sum2 = Calculator.add(10,15,20);
system.debug(sum2);

// public static integer add (List <integer> inList){
       // integer sum = 0;
       
List<integer> listInteger = new List<integer>();
listInteger.add(10);
listInteger.add(15);
listInteger.add(30);
integer sumList = Calculator.add(listInteger);
system.debug('sum is '+ sumList);




